import {helpers as h} from './shared.js';
import {renderHalo} from './halo.js';
import {renderDaybook,renderSignal} from './variants-b.js';
import {renderMosaic,renderFlow} from './variants-c.js';

const concepts=[
  {id:'halo',name:'Halo',tag:'Progress at the center',color:'#405c99',headline:'Make room for deep work.',description:'A single focus dial gives the day a clear center. The goal leads, the balance explains, and tasks stay within reach.',structure:'Radial progress + supporting panels',type:'Space Grotesk / DM Sans',shape:'Soft, generous corners',notes:['Daily focus is the strongest visual on the page.','Leisure and the ratio remain visible together.','A good fit if you start sessions more often than you manage tasks.'],render:renderHalo},
  {id:'daybook',name:'Daybook',tag:'Your day, on paper',color:'#a03d29',headline:'A little less dashboard.',description:'An editorial day planner puts the next task ahead of the numbers. Time reads like a ledger, and work becomes an agenda.',structure:'Agenda + typographic time ledger',type:'Georgia / DM Sans',shape:'Fine rules, open space',notes:['The next task gives the page a useful starting point.','Serif headings and time columns change the reading rhythm.','The dial gives way to a clear written record.'],render:renderDaybook},
  {id:'signal',name:'Signal',tag:'A precise control room',color:'#7d9828',headline:'Know where you stand.',description:'A compact instrument panel makes the numbers explicit. Goal, usage, and balance are readable without a stack of soft cards.',structure:'Numerical instruments + data grid',type:'Consolas / DM Sans',shape:'Crisp edges, modular borders',notes:['Strong contrast and exact values suit frequent check-ins.','The hourly chart moves closer to the main metrics.','Dense by choice; the clearest option for a data-first habit.'],render:renderSignal},
  {id:'mosaic',name:'Mosaic',tag:'Energy without clutter',color:'#b24421',headline:'Give the day some shape.',description:'A bold block composition turns totals and tasks into a poster. Different sizes tell you what matters before you read a label.',structure:'Asymmetric blocks + oversized type',type:'Space Grotesk / DM Sans',shape:'Bold rectangular color blocks',notes:['The grid uses scale to separate focus from supporting data.','Task completion feels tangible through a segmented count.','A more expressive direction with the same practical actions.'],render:renderMosaic},
  {id:'flow',name:'Flow',tag:'One next step',color:'#377294',headline:'Start with what is next.',description:'A calm route through now, next, and today. The task and action lead; progress and activity follow in a quiet, readable sequence.',structure:'Task-first route + horizontal balance',type:'DM Sans',shape:'Open space, subtle blue surfaces',notes:['Task context and Start focus sit together.','A horizontal balance strip replaces the central hero chart.','A good fit for lower visual pressure and a clear reading order.'],render:renderFlow}
];
const base=()=>({focus:90,leisure:35,goal:120,tasksDone:3,tasksGoal:5,credit:42,task:'Revise electrochemistry',frog:'Finish the practice paper',scenario:'ready',historyOpen:false,records:[{title:'Chemistry revision',hour:11,minutes:25,source:'Focus timer'},{title:'Project planning',hour:9,minutes:20,source:'Manual log'},{title:'Practice problems',hour:8,minutes:45,source:'TickTick'}]});
let states=Object.fromEntries(concepts.map(c=>[c.id,base()]));
let selected=concepts.find(c=>c.id===location.hash.slice(1))?.id??'halo';
let compare=false, width=390, scale=1, activeSheet=null, timer=null, toastTimeout, returnAction=null;
const tabs=document.querySelector('#concept-tabs'), stage=document.querySelector('#stage'), sheet=document.querySelector('#sheet');
function nav(){return `<nav class="app-nav" aria-label="App navigation">${[['home','Focus','focus'],['chart','Boundaries','boundaries'],['lock','Strict','strict'],['shield','Permalock','permalock'],['settings','Settings','settings']].map(([icon,label,action])=>`<button data-action="${action}" class="${action==='focus'?'active':''}" ${action==='focus'?'aria-current="page"':''}>${h.icon(icon)}<span>${label}</span></button>`).join('')}</nav><div class="android-gesture" aria-hidden="true"></div>`;}
function phone(c){return `<article class="phone-wrap" data-concept="${c.id}">${compare?`<div class="compare-title"><h2>${c.name}</h2><span>${c.tag}</span></div>`:''}<div class="phone ${c.id}" style="--phone-width: ${width}px; --scale: ${scale}"><div class="status-bar" aria-hidden="true"><span>9:41</span><span class="camera"></span><span class="status-icons">▂▃▅ <span class="status-battery"></span></span></div><div class="screen" tabindex="0" aria-label="${c.name} scrollable homepage"><div class="home-body">${c.render(states[c.id],h)}</div></div>${nav()}</div><span class="phone-caption">${compare?'':'Tap controls to try it · '}Scroll for the full day</span></article>`;}
function render(keepScroll=false){
  const focused=document.activeElement?.closest('[data-concept]');const focusAction=focused?document.activeElement?.dataset.action:null;const focusConcept=focused?.dataset.concept;
  const scroll=Object.fromEntries([...stage.querySelectorAll('[data-concept]')].map(el=>[el.dataset.concept,el.querySelector('.screen').scrollTop]));
  tabs.innerHTML=concepts.map((c,i)=>`<button class="concept-tab" data-select="${c.id}" aria-current="${!compare&&selected===c.id}" style="--swatch:${c.color}"><span class="number">0${i+1}</span><strong>${c.name}</strong><span class="swatch"></span></button>`).join('');
  stage.className=`stage ${compare?'compare-stage':''}`;
  const c=concepts.find(c=>c.id===selected);
  stage.innerHTML=compare?concepts.map(phone).join(''):`<aside class="concept-story"><span class="story-tag">${c.tag}</span><h2>${c.headline}</h2><p class="story-description">${c.description}</p><div class="story-facts"><div><b>COMPOSITION</b><span>${c.structure}</span></div><div><b>TYPOGRAPHY</b><span>${c.type}</span></div><div><b>FORM</b><span>${c.shape}</span></div></div></aside>${phone(c)}<aside class="stage-notes"><h3>What changes</h3>${c.notes.map((n,i)=>`<p><span class="note-number">0${i+1}</span>${n}</p>`).join('')}<h3>What stays</h3><p>Timer · Work log · Tasks<br>Eat the Frog · Time balance<br>Usage · History · Scroll bank<br>All app destinations</p></aside>`;
  if(keepScroll)stage.querySelectorAll('[data-concept]').forEach(el=>el.querySelector('.screen').scrollTop=scroll[el.dataset.concept]??0);
  if(focusAction)stage.querySelector(`[data-concept="${focusConcept}"] [data-action="${focusAction}"]`)?.focus({preventScroll:true});
  document.querySelector('#compare').textContent=compare?'Single concept ↙':'Compare all five ↗';document.querySelector('#compare').setAttribute('aria-pressed',compare);
}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.classList.remove('visible'),2600);}
function closeSheet(){if(timer){clearInterval(timer.interval);timer=null;}const id=activeSheet;sheet.close();activeSheet=null;if(id&&returnAction)stage.querySelector(`[data-concept="${id}"] [data-action="${returnAction}"]`)?.focus({preventScroll:true});}
function showSheet(id,title,content){
  if(!sheet.open)returnAction=document.activeElement?.closest('[data-action]')?.dataset.action??null;
  const c=concepts.find(c=>c.id===id);activeSheet=id;sheet.className=c.id;sheet.style.setProperty('--scale',scale);
  sheet.querySelector('#sheet-content').innerHTML=`<div class="sheet-inner"><header class="sheet-head"><h2 id="sheet-title">${title}</h2><button class="icon-button" data-sheet="close" aria-label="Close">${h.icon('close')}</button></header><p class="sheet-hint">Interactive design preview · Sample data only</p>${content}</div>`;
  if(!sheet.open)sheet.showModal();
  (sheet.querySelector('input:not([type="checkbox"]),select')??sheet.querySelector('button'))?.focus();
}
function openTimer(id){showSheet(id,'Start focus',`<form id="timer-form"><p>A session for the task in front of you.</p><label for="timer-task">Session title</label><input id="timer-task" name="title" value="${h.escape(states[id].task)}" maxlength="100" required><label for="timer-duration">Duration</label><select id="timer-duration" name="minutes"><option value="25">25 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option></select><button class="action-button primary" type="submit">${h.icon('timer')} Start session</button></form>`);}
function openLog(id){showSheet(id,'Log work',`<form id="log-form"><label for="work-title">What did you work on?</label><input id="work-title" name="title" placeholder="e.g. Chemistry revision" maxlength="100" required><label for="work-minutes">Minutes focused</label><input id="work-minutes" name="minutes" type="number" min="1" max="600" value="25" required><button class="action-button primary" type="submit">Save work</button></form>`);}
function record(id,title,minutes,source){let s=states[id];s.focus+=minutes;s.records.unshift({title,hour:14,minutes,source});render(true);toast(`${minutes} minutes added to this concept's demo`);}
function openTasks(id){const s=states[id];if(['signedout','error'].includes(s.scenario)){showSheet(id,'TickTick tasks',`<p>${s.scenario==='error'?'Couldn’t load tasks. Retry the preview state.':'Connect TickTick to see your tasks.'}</p>${h.button(s.scenario==='error'?'Retry':'Preview connected tasks',s.scenario==='error'?'retry':'connect','primary')}`);return;}showSheet(id,'Tasks today',`<p>Try checking a task. The homepage count updates.</p>${['Read chapter notes','Organize study desk','Project planning',s.task,'Finish the practice paper'].map((t,i)=>`<label class="sheet-task"><input type="checkbox" data-task-check="${i}" ${i<s.tasksDone?'checked':''}><span>${h.escape(t)}</span></label>`).join('')}`);}
function openFrog(id){const s=states[id];showSheet(id,'Eat the Frog',`<p>Choose one task to finish before your distractions. The preview does not block apps.</p>${s.frog?`<div class="sheet-summary"><strong>Current commitment</strong><p>${h.escape(s.frog)}</p></div>`:''}<form id="frog-form"><label for="frog-title">Choose or enter a task</label><input id="frog-title" name="title" list="frog-options" value="${h.escape(s.frog||s.task)}" maxlength="120" required><datalist id="frog-options"><option value="Revise electrochemistry"><option value="Finish the practice paper"></datalist><button class="action-button primary" type="submit">${s.frog?'Update demo task':'Choose task'}</button></form>${s.frog?'<button class="text-action" data-sheet="complete-frog">Mark demo task complete</button>':''}`);}
function account(id){showSheet(id,'Account',`<div class="sheet-summary"><strong>Aniru · Sample account</strong><p>Android, Windows, and Chrome account entry stays here.</p></div><p>This design lab has no live authentication or sync connection.</p>${h.button('View TickTick tasks','tasks','secondary')}`);}
function action(id,a){
  const s=states[id];
  if(a==='timer')return openTimer(id);if(a==='log')return openLog(id);if(a==='tasks')return openTasks(id);if(a==='frog')return openFrog(id);if(a==='account')return account(id);
  if(a==='history'){s.historyOpen=!s.historyOpen;return render(true);}
  if(a==='retry'||a==='connect'){s.scenario='ready';document.querySelector('#scenario').value='ready';render(true);closeSheet();return toast('Connected tasks shown in this demo');}
  if(a==='focus'){stage.querySelector(`[data-concept="${id}"] .screen`).scrollTo({top:0,behavior:'smooth'});return;}
  if(a==='settings')return showSheet(id,'Settings',`<div class="sheet-summary"><strong>Daily focus goal</strong><p>${h.duration(s.goal)} per day</p></div><form id="goal-form"><label for="goal">Focus goal in minutes</label><input id="goal" name="goal" type="number" min="15" max="600" value="${s.goal}" required><button class="action-button primary" type="submit">Update demo goal</button></form><button class="text-action" data-action="account">Open account</button><p>The five home designs are selected from the gallery above.</p>`);
  if(a==='permissions')return showSheet(id,'Finish setup',`<div class="sheet-summary"><strong>Usage access</strong><p>Needed to measure selected leisure apps.</p></div><div class="sheet-summary"><strong>Accessibility</strong><p>Needed to enforce app and website boundaries.</p></div><p>In Android, these open the corresponding system permission screens.</p><button class="action-button primary" data-sheet="permissions-done">Preview setup complete</button>`);
  if(a==='nuke')return showSheet(id,'Emergency lockdown',`<p>Nuke starts the app’s guided emergency lockdown. It stays separate from ordinary focus sessions.</p><p class="danger-text">This is a preview. No apps will be blocked.</p><button class="action-button primary" data-sheet="nuke-preview">Preview guided lockdown</button><button class="text-action" data-sheet="close">Cancel</button>`);
  if(a==='boundaries')return showSheet(id,'Boundaries',`<p>Your current apps, sites, limits, and merged groups remain one tap away.</p><div class="sheet-summary"><strong>YouTube</strong><p>Selected leisure boundary · ${s.leisure}m today</p></div><div class="sheet-summary"><strong>Social media</strong><p>Merged cross-device group · Sample boundary</p></div><p>Boundary editing remains on its existing screen in the app.</p>`);
  if(a==='strict')return showSheet(id,'Strict Mode',`<p>Keep the existing commitment screen, with duration, presets, automation, and approval controls.</p><div class="sheet-summary"><strong>Commitment status</strong><p>No active commitment in this sample.</p></div><p>Homepage styling does not change enforcement or unlock rules.</p>`);
  if(a==='permalock')return showSheet(id,'Permalock',`<p>The permanent-boundary screen remains a dedicated destination.</p><div class="sheet-summary"><strong>Permanent boundaries</strong><p>No permanent blocks in this sample.</p></div>`);
  toast(`Preview action: ${a}`);
}
tabs.addEventListener('click',e=>{const el=e.target.closest('[data-select]');if(!el)return;selected=el.dataset.select;compare=false;location.hash=selected;document.querySelector('#scenario').value=states[selected].scenario;render();});
document.querySelector('#compare').addEventListener('click',()=>{compare=!compare;render();});
document.querySelector('#phone-width').addEventListener('change',e=>{width=Number(e.target.value);render(true);});
document.querySelector('#text-scale').addEventListener('change',e=>{scale=Number(e.target.value);render(true);});
function changeScenario(value){for(const c of concepts){const s=states[c.id]=base();s.scenario=value;if(value==='behind'){s.focus=30;s.leisure=55;s.records=[{title:'Morning revision',hour:8,minutes:30,source:'Focus timer'}];}if(value==='empty'){Object.assign(s,{focus:0,leisure:0,tasksDone:0,credit:0,frog:'',records:[]});}}render();}
document.querySelector('#scenario').addEventListener('change',e=>changeScenario(e.target.value));
document.querySelector('#reset').addEventListener('click',()=>{closeSheet();changeScenario(document.querySelector('#scenario').value);toast('All demo data reset');});
stage.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)action(b.closest('[data-concept]').dataset.concept,b.dataset.action);});
sheet.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-sheet]');if(!b)return;if(b.dataset.action)return action(activeSheet,b.dataset.action);const id=activeSheet;if(b.dataset.sheet==='close')return closeSheet();if(b.dataset.sheet==='complete-frog'){states[id].frog='';closeSheet();render(true);toast('Frog task completed in this demo');}if(b.dataset.sheet==='permissions-done'){states[id].scenario='ready';document.querySelector('#scenario').value='ready';closeSheet();render(true);}if(b.dataset.sheet==='nuke-preview')showSheet(id,'Guided lockdown',`<p>Take ten minutes to reset. The Android app’s guided flow would begin here.</p><div class="timer-readout">10:00</div><p>Preview only. Nothing has been activated.</p><button class="action-button primary" data-sheet="close">Back to focus</button>`);if(b.dataset.sheet==='finish-timer'){const t=timer;closeSheet();record(id,t.title,t.minutes,'Focus timer preview');}});
sheet.addEventListener('change',e=>{if(e.target.matches('[data-task-check]')){states[activeSheet].tasksDone=sheet.querySelectorAll('[data-task-check]:checked').length;render(true);}});
sheet.addEventListener('submit',e=>{e.preventDefault();const form=e.target;if(!form.reportValidity())return;const data=new FormData(form), id=activeSheet;
  if(form.id==='log-form'){const title=String(data.get('title')).trim();if(!title){form.querySelector('input').setCustomValidity('Enter a work title.');return form.reportValidity();}closeSheet();record(id,title,Number(data.get('minutes')),'Manual log');}
  if(form.id==='frog-form'){const title=String(data.get('title')).trim();if(!title)return;states[id].frog=title;closeSheet();render(true);toast('Frog task saved in this demo');}
  if(form.id==='goal-form'){states[id].goal=Number(data.get('goal'));closeSheet();render(true);toast('Demo goal updated');}
  if(form.id==='timer-form'){const minutes=Number(data.get('minutes')), title=String(data.get('title')).trim();showSheet(id,'Focus session',`<p>${h.escape(title)}</p><div id="live-timer" class="timer-readout">${minutes}:00</div><p>Timer interaction preview. Finish adds the selected duration to sample data.</p><button class="action-button primary" data-sheet="finish-timer">Finish demo session</button><button class="text-action" data-sheet="close">Cancel session</button>`);const end=Date.now()+minutes*60000;timer={title,minutes,interval:setInterval(()=>{const remaining=Math.max(0,Math.ceil((end-Date.now())/1000));const el=document.querySelector('#live-timer');if(el)el.textContent=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;if(!remaining){closeSheet();record(id,title,minutes,'Focus timer preview');}},500)};}
});
sheet.addEventListener('cancel',e=>{e.preventDefault();closeSheet();});
sheet.addEventListener('click',e=>{if(e.target===sheet){const r=sheet.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeSheet();}});
window.addEventListener('hashchange',()=>{const c=concepts.find(c=>c.id===location.hash.slice(1));if(c&&c.id!==selected){selected=c.id;compare=false;document.querySelector('#scenario').value=states[selected].scenario;render();}});
render();
