export const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const icon = name => `<svg class="icon" width="20" height="20" aria-hidden="true"><use href="icons.svg#${escape(name)}"></use></svg>`;
export const button = (label, action, extraClass = '') => `<button type="button" class="action-button ${extraClass}" data-action="${escape(action)}">${label}</button>`;
export const duration = n => n == null ? 'Loading…' : n >= 60 ? `${Math.floor(n/60)}h ${Math.round(n%60)}m` : `${Math.round(n)}m`;
const loaded = s => s.scenario !== 'loading';
const taskUnavailable = s => ['loading','error','signedout'].includes(s.scenario);
export function head(s, title='Focus today') {
  return `<header class="app-head"><div class="app-date">Wednesday, 30 September</div><div class="app-title-row"><h2>${escape(title)}</h2><div class="head-actions"><button class="icon-button nuke-button" data-action="nuke" aria-label="Nuke: emergency lockdown" title="Emergency lockdown">${icon('bolt')}</button><button class="icon-button" data-action="settings" aria-label="Settings">${icon('settings')}</button><button class="icon-button avatar" data-action="account" aria-label="Account">A</button></div></div></header>`;
}
export function setup(s) {return s.scenario==='setup' ? `<div class="setup-banner">${icon('shield')}<div><strong>Finish setup</strong><p>Usage access is needed for protection.</p></div>${button('Set up','permissions','small')}</div>` : '';}
export function ratio(s) {
  let value, title, detail;
  if(!loaded(s)||s.scenario==='setup') {value='Unavailable';title='Waiting for usage data';detail='Goal 2:1 focus to leisure';}
  else if(!s.focus&&!s.leisure) {value='A fresh start';title='Make time for focus';detail='Goal 2:1 focus to leisure';}
  else if(!s.leisure) {value='No leisure yet';title='Focus is ahead';detail='Goal 2:1 focus to leisure';}
  else {value=`${(s.focus/s.leisure).toFixed(1)}:1`; const behind=s.focus/s.leisure<2; title=behind?'Leisure is ahead':'On track';detail=behind?`${Math.max(0,Math.ceil(s.leisure*2-s.focus))}m more focus to reach 2:1`:'Meeting your 2:1 focus-to-leisure goal';}
  return `<div class="ratio ${loaded(s)&&s.leisure&&s.focus/s.leisure<2?'behind':''}"><div class="ratio-top"><strong>${escape(value)}</strong><span>${escape(title)}</span></div><p>${escape(detail)}</p></div>`;
}
export function metrics(s) {return `<div class="metrics"><div><span>Focus</span><strong>${loaded(s)?duration(s.focus):'Loading…'}</strong><small>of ${duration(s.goal)} goal</small></div><div><span>Leisure</span><strong>${loaded(s)&&s.scenario!=='setup'?duration(s.leisure):'Unavailable'}</strong><small>Selected boundaries</small></div></div>`;}
export function actions(){return `<div class="primary-actions">${button(`${icon('timer')}<span>Start focus</span>`,'timer','primary')}${button(`${icon('plus')}<span>Log work</span>`,'log','secondary')}</div>`;}
export function task(s) {
  if(s.scenario==='loading')return `<section class="section next-task" data-view="next-task"><div class="section-heading"><h3>Up next</h3>${icon('list')}</div><p class="loading-text">Loading your tasks…</p></section>`;
  if(s.scenario==='error')return `<section class="section next-task" data-view="next-task"><h3>Tasks couldn't load</h3><p>Your local timer still works.</p>${button(`${icon('refresh')}Retry TickTick`,'retry','secondary')}</section>`;
  if(s.scenario==='signedout')return `<section class="section next-task" data-view="next-task"><h3>Bring your tasks here</h3><p>Connect TickTick to see your next task.</p>${button('Connect TickTick','connect','secondary')}</section>`;
  if(s.scenario==='empty')return `<section class="section next-task" data-view="next-task"><h3>A clear agenda</h3><p>Choose a task or start an untitled session.</p>${button('Open tasks','tasks','text-action')}</section>`;
  return `<section class="section next-task" data-view="next-task"><div class="section-heading"><h3>Up next</h3><span class="meta">TickTick</span></div><button class="task-link" data-action="tasks"><span><strong>${escape(s.task)}</strong><small>Chemistry · Today</small></span>${icon('arrow')}</button></section>`;
}
export function frog(s){return `<section class="section frog-section" data-view="frog"><div class="section-heading"><h3>${icon('target')} Eat the Frog</h3><button class="text-action" data-action="frog">${s.frog?'Change':'Choose'}</button></div><p class="frog-title">${s.frog?escape(s.frog):'Choose the one task that matters most.'}</p><p class="muted">${s.frog?'Finish it before opening your distractions.':'Pick from TickTick or enter a task yourself.'}</p>${button(s.frog?'Review commitment':'Choose a task','frog','secondary')}</section>`;}
export function tasks(s){return `<section class="section tasks-section" data-view="tasks"><div class="section-heading"><h3>Tasks today</h3>${button('Open','tasks','text-action')}</div>${taskUnavailable(s)?`<p>${s.scenario==='loading'?'Loading tasks…':s.scenario==='error'?'Task progress unavailable':'Connect TickTick for task progress'}</p>`:`<div class="task-progress"><strong>${s.tasksDone}<span> / ${s.tasksGoal}</span></strong><span>completed</span></div><div class="task-dots" aria-label="${s.tasksDone} of ${s.tasksGoal} tasks completed">${Array.from({length:s.tasksGoal},(_,i)=>`<span class="${i<s.tasksDone?'done':''}"></span>`).join('')}</div>`}</section>`;}
export function chart(s){
  const rows=s.records??[]; const hours=Array.from({length:24},(_,h)=>rows.filter(r=>r.hour===h).reduce((v,r)=>v+r.minutes,0));const max=Math.max(0,...hours);
  return `<section class="section day-chart" data-view="chart"><div class="section-heading"><h3>Focus through the day</h3><span class="meta">${loaded(s)?`Max ${max}m`:'Loading'}</span></div>${!loaded(s)?'<p>Loading your focus records…</p>':!max?'<p>Your first focus session will appear here.</p>':`<div class="hour-bars" role="img" aria-label="Hourly focus in minutes: ${hours.map((m,i)=>m?`${i}:00, ${m} minutes`:null).filter(Boolean).join('; ')}">${hours.map(m=>`<span class="${m?'has-focus':''}" style="height:${Math.max(3,m/max*100)}%"></span>`).join('')}</div><div class="hour-labels"><span>00</span><span>06</span><span>12</span><span>18</span><span>23</span></div>`}</section>`;
}
export function history(s){const rows=s.records??[];return `<section class="section history-section" data-view="history"><div class="section-heading"><h3>Recent work</h3><button class="text-action" data-action="history" aria-expanded="${s.historyOpen}">${s.historyOpen?'Show less':'Show all'}</button></div>${!loaded(s)?'<p>Loading work history…</p>':!rows.length?'<p>No work logged yet. Start focus or log a session.</p>':rows.slice(0,s.historyOpen?rows.length:2).map(r=>`<div class="history-row"><span class="history-icon">${icon('check')}</span><div><strong>${escape(r.title)}</strong><small>${String(r.hour).padStart(2,'0')}:00 · ${escape(r.source??'Focus timer')}</small></div><b>${duration(r.minutes)}</b></div>`).join('')}</section>`;}
export function bank(s){return `<aside class="bank" data-view="bank">${icon('phone')}<div><span>Scroll bank</span><strong>${loaded(s)?duration(s.credit):'Loading…'}</strong></div><small>Credit from focus;<br>separate from today's ratio.</small></aside>`;}
export function usage(s){return `<section class="section usage-section" data-view="usage"><div class="section-heading"><h3>Screen time</h3>${icon('phone')}</div>${!loaded(s)?'<p>Reading today’s usage…</p>':s.scenario==='setup'?`<p>Usage access is off. Enable it to see screen time.</p>${button('Enable usage access','permissions','secondary')}`:s.scenario==='empty'?'<p>No tracked screen time yet.</p>':`<div class="usage-row"><span>Most used · YouTube</span><strong>${duration(Math.min(25,s.leisure))}</strong></div><div class="usage-row"><span>All tracked apps</span><strong>${duration(s.leisure+40)}</strong></div><p class="muted">Leisure counts only your selected boundaries.</p>`}</section>`;}
export const helpers={escape,icon,button,duration,head,setup,ratio,metrics,actions,task,frog,tasks,chart,history,bank,usage};
